# Test map generator: builds src/maps/town.map.js in Tiled-JSON shape.
# Usage: pwsh tools/mapgen.ps1  (ASCII only on purpose: avoids PS encoding issues)
# NOTE: Chinese comments break Windows PowerShell parsing without a UTF-8 BOM.
$W = 40; $H = 30
$G = @{ grass=1; path=2; water=3; tree=4; wall=5; roof=6; tower=7; flower=8; bench=9; pier=10 }

$data = New-Object 'int[]' ($W * $H)
for ($i = 0; $i -lt $data.Length; $i++) { $data[$i] = $G.grass }

# Rect fill (inclusive bounds; later fills win)
function Fill([int]$r0, [int]$r1, [int]$c0, [int]$c1, [int]$gid) {
  for ($r = $r0; $r -le $r1; $r++) { for ($c = $c0; $c -le $c1; $c++) { $data[$r * $W + $c] = $gid } }
}
function Cell([int]$r, [int]$c, [int]$gid) { $data[$r * $W + $c] = $gid }

# ---- Terrain (zones per docs/drafts/MAP_DRAFTS.md) ----
Fill 0 29 0 1  $G.water                     # river (west edge, full height)
Fill 10 17 2 3 $G.path                      # riverside path
Cell 17 3 $G.bench                          # bench (chen_po bread spot)
Fill 18 22 2 3 $G.flower                    # reeds ("the light" legend spot)
Fill 25 28 2 4 $G.pier                      # wooden pier (lao_zhou fishing)
Fill 26 29 15 25 $G.path                    # town entrance road
Fill 9 16 13 27 $G.path                     # square
Fill 10 11 14 15 $G.flower                  # flower bed
Cell 15 24 $G.flower; Cell 15 25 $G.flower  # flower bed
Fill 10 12 19 20 $G.tower                   # clock tower
Fill 3 4 12 20 $G.roof                      # cafe roof
Fill 5 6 12 20 $G.wall                      # cafe walls
Fill 7 7 15 17 $G.path                      # cafe door
Fill 3 4 24 30 $G.roof                      # minsu roof
Fill 5 6 24 30 $G.wall                      # minsu walls
Fill 7 7 26 27 $G.path                      # minsu door
Fill 10 11 5 10 $G.roof                     # library roof
Fill 12 13 5 10 $G.wall                     # library walls
Cell 14 7 $G.path                           # library door
Fill 10 11 30 36 $G.roof                    # grocery roof
Fill 12 13 30 36 $G.wall                    # grocery walls
Cell 14 33 $G.path                          # grocery door
Fill 17 17 28 34 $G.roof                    # chen_po house roof
Fill 18 19 28 34 $G.wall                    # chen_po house walls
Cell 20 30 $G.path                          # chen_po door
Fill 21 21 28 33 $G.roof                    # lao_zhou house roof
Fill 22 23 28 33 $G.wall                    # lao_zhou house walls
Cell 24 30 $G.path                          # lao_zhou door
Fill 21 22 34 36 $G.flower                  # lao_zhou garden
Fill 0 6 32 39 $G.tree                      # north woods
Fill 24 29 31 39 $G.tree                    # south woods
Fill 0 4 4 9 $G.tree                        # northwest woods

# ---- Event objects (pixel coords = tile coords * 32) ----
$objects = @(
  @{ id=1;  name='spawn';            x=640;  y=896;  width=32;  height=32  },
  @{ id=2;  name='door_cafe';        x=512;  y=224;  width=96;  height=32  },
  @{ id=3;  name='door_minsu';       x=832;  y=224;  width=64;  height=32  },
  @{ id=4;  name='door_library';     x=224;  y=448;  width=32;  height=32  },
  @{ id=5;  name='door_grocery';     x=1056; y=448;  width=32;  height=32  },
  @{ id=6;  name='bench_bread';      x=96;   y=544;  width=32;  height=32  },
  @{ id=7;  name='river_light';      x=64;   y=640;  width=64;  height=64  },
  @{ id=8;  name='old_zhou_fishing'; x=96;   y=832;  width=96;  height=64  },
  @{ id=9;  name='lin_shu';    type='npc'; x=512;  y=256;  width=32;  height=48  },
  @{ id=10; name='su_li';      type='npc'; x=256;  y=480;  width=32;  height=48  },
  @{ id=11; name='lao_zhou';   type='npc'; x=96;   y=832;  width=32;  height=48  },
  @{ id=12; name='a_he';       type='npc'; x=1056; y=480;  width=32;  height=48  },
  @{ id=13; name='xiao_man';   type='npc'; x=864;  y=256;  width=32;  height=48  },
  @{ id=14; name='chen_po';    type='npc'; x=992;  y=640;  width=32;  height=48  }
)

# PS 5.1 ConvertTo-Json wraps int[] as {"value":[...]} - bypass with placeholder injection
$dataStr = ($data -join ', ')

$map = [ordered]@{
  type='map'; version='1.10'; orientation='orthogonal'; renderorder='right-down'
  width=$W; height=$H; tilewidth=32; tileheight=32; infinite=$false
  layers=@(
    [ordered]@{ name='ground'; type='tilelayer'; x=0; y=0; width=$W; height=$H; visible=$true; opacity=1; data='__DATA__' },
    [ordered]@{ name='events'; type='objectgroup'; x=0; y=0; visible=$true; opacity=1; objects=$objects }
  )
  tilesets=@([ordered]@{ firstgid=1; name='test_tiles'; image=''; imagewidth=0; imageheight=0; tilewidth=32; tileheight=32; columns=1; tilecount=10 })
}

$json = ($map | ConvertTo-Json -Depth 8) -replace '"__DATA__"', "[ $dataStr ]"
$js = "// AUTO-GENERATED by tools/mapgen.ps1 - do not edit. Tiled JSON (.tmj) subset.`nwindow.TOWN_MAP = $json;"
$out = Join-Path $PSScriptRoot '..\src\maps\town.map.js'
$dir = Split-Path $out -Parent
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
Set-Content -Path $out -Value $js -Encoding ascii
Write-Output "OK: generated $out (${W}x${H} = $($data.Length) tiles)"
