// tools/personas2js.js — 由 data/npcs/*.json 生成 src/personas.js
// 原因：file:// 协议下浏览器无法 fetch 本地 JSON，故把人物卡内嵌为 JS。
// 用法：node tools/personas2js.js（改完 data/npcs/*.json 后重跑一次）
const fs = require('fs');
const path = require('path');

const dir = path.join(__dirname, '..', 'data', 'npcs');
const files = fs.readdirSync(dir).filter(f => f.endsWith('.json')).sort();

const out = [
  '// AUTO-GENERATED by tools/personas2js.js - do not edit.',
  '// 数据源：data/npcs/*.json（改人物卡请改 JSON 后重跑生成）',
  'window.PERSONAS = {'
];
for (const f of files) {
  const p = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8'));
  out.push('  ' + JSON.stringify(p.id) + ': ' + JSON.stringify(p, null, 2) + ',');
}
out.push('};');

const target = path.join(__dirname, '..', 'src', 'personas.js');
fs.writeFileSync(target, out.join('\n'), 'utf8');
console.log('OK: generated ' + target + ' from ' + files.length + ' NPCs: ' + files.map(f => f.replace('.json', '')).join(', '));
